BUGFIX: data may contain NaN (some frames left out) thus needs to be float
Before
ValueError: cannot convert float NaN to integer
was triggered.

Signed-off-by: Ivo Alxneit <ivo.alxneit@psi.ch>