Catch typical mistake early
Early versions had `read_drift` a bool. Thus old scripts might fail with
an confusion error message

reading data demo.pts ..Traceback (most recent call last):
  File "./plot_maps.py", line 27, in <module>
    dc = JEOL_pts(file, E_cutoff=10.0, read_drift=True)
  File "/home/alxneit/miniconda3/envs/analysis/lib/python3.13/site-packages/JEOL_eds/JEOL_pts.py", line 263, in __init__
    read_drift = read_drift.lower()
                 ^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'lower'



Signed-off-by: Ivo Alxneit <ivo.alxneit@psi.ch>